import { randomBytes, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir, userInfo } from "node:os";
import { join } from "node:path";
import type { AddressInfo } from "node:net";
import { Pool } from "pg";
import { describe, expect, it } from "vitest";
import { createApiServer } from "../../apps/server/src/index.js";
import { LocalIdentity } from "../../apps/server/src/identity.js";
import { migrateDatabase } from "../../apps/server/src/migrations.js";
import { previewStudentDeletion, cleanupExpiredSecrets, retentionCandidates } from "../../apps/server/src/operations.js";
import { PostgresRuntimeStore } from "../../apps/server/src/runtime-store.js";

const socket = process.env.PVF_TEST_PG_SOCKET;
describe.skipIf(!socket || process.env.PVF_TEST_PG_RESTART === "1")("guarded operations on disposable PostgreSQL", () => {
  it("archives, restores into a separate database, deletes dependent evidence and cleans secrets", async () => {
    if (!socket?.startsWith("/tmp/pvf-postgres-test-")) throw new Error("Disposable socket required");
    const suffix = randomUUID().replaceAll("-", "");
    const source = `ops_${suffix}`;
    const target = `restored_${suffix}`;
    const admin = new Pool({ host: socket, database: "postgres" });
    await admin.query(`CREATE DATABASE ${source}`);
    await admin.query(`CREATE DATABASE ${target}`);
    await admin.end();
    const pool = new Pool({ host: socket, database: source });
    const restored = new Pool({ host: socket, database: target });
    const directory = await mkdtemp(join(tmpdir(), "pvf-ops-"));
    const archive = join(directory, "fictional.backup");
    let server: ReturnType<typeof createApiServer> | undefined;
    try {
      await migrateDatabase(pool);
      const store = new PostgresRuntimeStore(pool);
      const key = randomBytes(32);
      const identity = new LocalIdentity(() => store.connection(), key);
      const password = randomUUID();
      await store.transaction(() => identity.provisionTeacher("ops-teacher", password));
      server = createApiServer("/unused/ops.json", { database: pool, identity: { origin: "https://classroom.test", receiptKey: key.toString("hex") } });
      await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve));
      const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api/v1`;
      type Session = { cookie: string; csrf: string };
      const request = async (path: string, body?: Record<string, unknown>, session?: Session, method = body ? "POST" : "GET") => {
        const response = await fetch(base + path, { method, headers: { origin: "https://classroom.test", "content-type": "application/json", ...(session ? { cookie: session.cookie, "x-csrf-token": session.csrf } : {}), ...(body?.commandId ? { "idempotency-key": String(body.commandId) } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
        return { status: response.status, body: await response.json(), cookie: response.headers.get("set-cookie") };
      };
      const teacherLogin = await request("/auth/teacher/session", { username: "ops-teacher", password });
      expect(teacherLogin.status).toBe(200);
      const teacher = { cookie: teacherLogin.cookie!.split(";")[0], csrf: teacherLogin.body.csrfToken };
      const classOne = (await request("/teacher/classes", { commandId: "class-one", name: "Fictional Class One", timezone: "UTC" }, teacher)).body;
      const classTwo = (await request("/teacher/classes", { commandId: "class-two", name: "Fictional Class Two", timezone: "UTC" }, teacher)).body;
      const first = (await request(`/teacher/classes/${classOne.id}/students`, { commandId: "student-one", username: "first", alias: "First" }, teacher)).body;
      const second = (await request(`/teacher/classes/${classTwo.id}/students`, { commandId: "student-two", username: "second", alias: "Second" }, teacher)).body;
      const studentLogin = await request("/auth/student/session", { classCode: classOne.classCode, username: "first", pin: first.oneTimePin });
      const student = { cookie: studentLogin.cookie!.split(";")[0], csrf: studentLogin.body.csrfToken };
      const start = await request("/games/place-value-factory/attempts", { commandId: "start", profileRevision: 0, tabId: "ops-tab", levelId: "level-1" }, student);
      expect(start.status).toBe(201);
      let snapshot = start.body;
      const firstOrderId = snapshot.activeOrder.id;
      for (let slot = 0; slot < 5; slot++) {
        let remainder = snapshot.activeOrder.target;
        const representationA = [100000,10000,1000,100,10,1].map((denomination) => { const n = Math.floor(remainder / denomination); remainder %= denomination; return n; });
        const answer = await request(`/games/place-value-factory/attempts/${snapshot.attemptId}/orders/${snapshot.activeOrder.id}/responses`, { commandId: `answer-${slot}`, expectedRevision: snapshot.revision, leaseEpoch: snapshot.leaseEpoch, tabId: "ops-tab", representationA }, student);
        expect(answer.status).toBe(200);
        snapshot = answer.body.snapshot;
      }
      expect(snapshot.status).toBe("completed");
      await pool.query("UPDATE pvf_game_profile SET certifications='[\"fictional-certification\"]'::jsonb WHERE student_id=$1", [first.student.id]);
      const before = (await pool.query("SELECT (SELECT count(*)::int FROM pvf_attempt) attempts,(SELECT count(*)::int FROM pvf_order) orders,(SELECT count(*)::int FROM pvf_response) answers,(SELECT count(*)::int FROM pvf_skill_evidence) evidence,(SELECT count(*)::int FROM pvf_command_receipt) receipts")).rows[0];
      const sourceUrl = `postgresql://${userInfo().username}@localhost/${source}?host=${encodeURIComponent(socket)}`;
      const targetUrl = `postgresql://${userInfo().username}@localhost/${target}?host=${encodeURIComponent(socket)}`;
      const backupKey = randomBytes(32).toString("hex");
      const script = "scripts/backup-restore.mjs";
      const backup = spawnSync(process.execPath, [script, "backup", `--archive=${archive}`, `--confirm-source-db=${source}`], { cwd: process.cwd(), env: { ...process.env, PVF_BACKUP_SOURCE_URL: sourceUrl, PVF_BACKUP_KEY: backupKey }, encoding: "utf8" });
      expect(backup.status, backup.stderr).toBe(0);
      expect((await readFile(archive)).subarray(0, 7).toString()).toBe("PVFENC1");
      const wrongKey = spawnSync(process.execPath, [script, "restore", `--archive=${archive}`, "--execute", `--confirm-target-db=${target}`], { cwd: process.cwd(), env: { ...process.env, PVF_BACKUP_SOURCE_URL: sourceUrl, PVF_RESTORE_TARGET_URL: targetUrl, PVF_BACKUP_KEY: randomBytes(32).toString("hex") }, encoding: "utf8" });
      expect(wrongKey.status).not.toBe(0);
      expect((await restored.query("SELECT count(*)::int AS n FROM pg_class WHERE relnamespace='public'::regnamespace AND relkind='r'")).rows[0].n).toBe(0);
      const restore = spawnSync(process.execPath, [script, "restore", `--archive=${archive}`, "--execute", `--confirm-target-db=${target}`], { cwd: process.cwd(), env: { ...process.env, PVF_BACKUP_SOURCE_URL: sourceUrl, PVF_RESTORE_TARGET_URL: targetUrl, PVF_BACKUP_KEY: backupKey }, encoding: "utf8" });
      expect(restore.status, restore.stderr).toBe(0);
      const after = (await restored.query("SELECT (SELECT count(*)::int FROM pvf_attempt) attempts,(SELECT count(*)::int FROM pvf_order) orders,(SELECT count(*)::int FROM pvf_response) answers,(SELECT count(*)::int FROM pvf_skill_evidence) evidence,(SELECT count(*)::int FROM pvf_command_receipt) receipts")).rows[0];
      expect(after).toEqual(before);
      expect((await restored.query("SELECT spec FROM pvf_order WHERE id=$1", [firstOrderId])).rows[0].spec).toEqual((await pool.query("SELECT spec FROM pvf_order WHERE id=$1", [firstOrderId])).rows[0].spec);
      expect((await restored.query("SELECT representation_a,validation FROM pvf_response")).rows).toEqual((await pool.query("SELECT representation_a,validation FROM pvf_response")).rows);
      expect((await restored.query("SELECT certifications FROM pvf_game_profile WHERE student_id=$1", [first.student.id])).rows[0].certifications).toEqual(["fictional-certification"]);
      expect((await restored.query("SELECT status,awarded_tier,transfer_star FROM pvf_attempt WHERE id=$1", [snapshot.attemptId])).rows).toEqual((await pool.query("SELECT status,awarded_tier,transfer_star FROM pvf_attempt WHERE id=$1", [snapshot.attemptId])).rows);
      const restoredServer = createApiServer("/unused/restored-ops.json", { database: restored, identity: { origin: "https://classroom.test", receiptKey: key.toString("hex") } });
      await new Promise<void>((resolve) => restoredServer.listen(0, "127.0.0.1", resolve));
      try {
        const restoredBase = `http://127.0.0.1:${(restoredServer.address() as AddressInfo).port}/api/v1`;
        const restoredReport = await fetch(`${restoredBase}/teacher/classes/${classOne.id}/games/place-value-factory/report`, { headers: { origin: "https://classroom.test", cookie: teacher.cookie } });
        expect(restoredReport.status).toBe(200);
        expect((await restoredReport.json()).students[0]).toMatchObject({ submittedN: 5, eventuallyCorrectN: 5 });
      } finally {
        await new Promise<void>((resolve, reject) => restoredServer.close((error) => error ? reject(error) : resolve()));
      }
      const extraId = randomUUID();
      await pool.query("INSERT INTO pvf_identity(id,role,username,credential_hash) VALUES($1,'student','extra-fictional','fixture-only')", [extraId]);
      await pool.query("INSERT INTO pvf_student(id,class_id,username,alias) VALUES($1,$2,'extra-fictional','Extra Fictional')", [extraId, classOne.id]);
      await pool.query("INSERT INTO pvf_game_profile(student_id) VALUES($1)", [extraId]);
      expect((await request(`/teacher/classes/${classOne.id}/archive`, { commandId: "archive-one" }, teacher, "PATCH")).status).toBe(200);
      expect((await request(`/teacher/classes/${classOne.id}/archive`, { commandId: "archive-one" }, teacher, "PATCH")).status).toBe(200);
      expect((await request("/profile", undefined, student)).status).toBe(401);
      expect((await request("/auth/student/session", { classCode: classOne.classCode, username: "first", pin: first.oneTimePin })).status).toBe(401);
      expect((await request(`/teacher/classes/${classOne.id}/access`, { commandId: "enable-archived", enabled: true }, teacher, "PATCH")).status).toBe(403);
      expect(await retentionCandidates(pool, classOne.id, 30)).toHaveLength(0);
      await pool.query("UPDATE pvf_class SET archived_at=now()-interval '31 days' WHERE id=$1", [classOne.id]);
      expect(await retentionCandidates(pool, classOne.id, 30)).toHaveLength(2);
      const client = await pool.connect();
      const preview = await previewStudentDeletion(client, classOne.id, first.student.id);
      client.release();
      expect(preview.counts.attempts).toBe(1);
      expect(preview.counts.answers).toBe(5);
      const operationArgs = ["tsx", "scripts/operations.ts", "student-delete", `--class-id=${classOne.id}`, `--student-id=${first.student.id}`];
      const operationEnv = { ...process.env, PVF_OPERATIONS_DATABASE_URL: sourceUrl };
      const previewRun = spawnSync("npx", operationArgs, { cwd: process.cwd(), env: operationEnv, encoding: "utf8" });
      expect(previewRun.status, previewRun.stderr).toBe(0);
      expect(previewRun.stdout).not.toContain(first.student.id);
      const missingPolicy = spawnSync("npx", [...operationArgs, "--execute", `--confirm-db=${source}`], { cwd: process.cwd(), env: operationEnv, encoding: "utf8" });
      expect(missingPolicy.status).not.toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_student WHERE id=$1", [first.student.id])).rows[0].n).toBe(1);
      const deleteRun = spawnSync("npx", [...operationArgs, "--execute", `--confirm-db=${source}`], { cwd: process.cwd(), env: { ...operationEnv, PVF_BACKUP_RETENTION_DAYS: "30" }, encoding: "utf8" });
      expect(deleteRun.status, deleteRun.stderr).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_student WHERE id=$1", [first.student.id])).rows[0].n).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_response")).rows[0].n).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_command_receipt WHERE actor_id=$1", [first.student.id])).rows[0].n).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_student WHERE id=$1", [second.student.id])).rows[0].n).toBe(1);
      expect((await pool.query("SELECT backup_expiry_at>now() AS marked FROM pvf_operations_audit WHERE action='student_delete'")).rows[0].marked).toBe(true);
      const retentionRun = spawnSync("npx", ["tsx", "scripts/operations.ts", "retention", `--class-id=${classOne.id}`, "--execute", `--confirm-db=${source}`], { cwd: process.cwd(), env: { ...operationEnv, PVF_RETENTION_DAYS: "30", PVF_BACKUP_RETENTION_DAYS: "30" }, encoding: "utf8" });
      expect(retentionRun.status, retentionRun.stderr).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_student WHERE id=$1", [extraId])).rows[0].n).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_operations_audit WHERE action='retention_delete' AND backup_expiry_at>now()")).rows[0].n).toBe(1);
      await pool.query("UPDATE pvf_operations_audit SET created_at=now()-interval '40 days'");
      const auditArgs = ["tsx", "scripts/operations.ts", "audit-retention"];
      const auditEnv = { ...operationEnv, PVF_AUDIT_RETENTION_DAYS: "30" };
      const auditPreview = spawnSync("npx", auditArgs, { cwd: process.cwd(), env: auditEnv, encoding: "utf8" });
      expect(auditPreview.status, auditPreview.stderr).toBe(0);
      expect(JSON.parse(auditPreview.stdout).counts.deletedRecords).toBe(0);
      const auditExecute = spawnSync("npx", [...auditArgs, "--execute", `--confirm-db=${source}`], { cwd: process.cwd(), env: auditEnv, encoding: "utf8" });
      expect(auditExecute.status, auditExecute.stderr).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_operations_audit WHERE action='class_archive'")).rows[0].n).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_operations_audit WHERE action IN ('student_delete','retention_delete')")).rows[0].n).toBe(2);
      await pool.query("UPDATE pvf_operations_audit SET backup_expiry_at=now()-interval '1 day' WHERE backup_expiry_at IS NOT NULL");
      const expiredAudit = spawnSync("npx", [...auditArgs, "--execute", `--confirm-db=${source}`], { cwd: process.cwd(), env: auditEnv, encoding: "utf8" });
      expect(expiredAudit.status, expiredAudit.stderr).toBe(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_operations_audit WHERE action IN ('student_delete','retention_delete')")).rows[0].n).toBe(0);
      expect((await request(`/teacher/students/${first.student.id}/games/place-value-factory/report`, undefined, teacher)).status).toBe(404);
      await pool.query("UPDATE pvf_roster_receipt SET secret_expires_at=now()-interval '1 second' WHERE secret_ciphertext IS NOT NULL");
      const cleanup = await cleanupExpiredSecrets(pool);
      expect(cleanup.secrets).toBeGreaterThanOrEqual(0);
      expect((await pool.query("SELECT count(*)::int AS n FROM pvf_roster_receipt WHERE secret_ciphertext IS NOT NULL AND secret_expires_at<=now()")).rows[0].n).toBe(0);
    } finally {
      if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve()));
      await pool.end();
      await restored.end();
      await rm(directory, { recursive: true, force: true });
    }
  }, 60_000);
});
